#!/bin/env bash
set -Eeuox pipefail

if [ -z "$1" ] || [ -z "$2" ]; then
  echo "$0 should take 2 arguments!"
  echo "usage: $0 [url] [sha]"
  exit 1
fi

script_tmp=`mktemp`
curl $1 > $script_tmp
cat $script_tmp
sha_value=`sha256sum < $script_tmp | cut -d' ' -f 1`
if [ $sha_value = $2 ]; then
  (cat $script_tmp | bash)
else
  echo "SHA values does not match: expected $2, got $sha_value"
  exit -1
fi
